version: "3.5"

x-networks-service-template: &networks
  networks:
    - api

services:
  poc-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: poc-api-container
    <<: *networks
    volumes:
      - ./src:/poc-api/src
      - ./envs:/poc-api/envs
      - ./test:/poc-api/test
    ports:
      - "3000:3000"
    depends_on:
      - db-api

  db-api:
    container_name: db-api-container
    image: postgres:12-alpine3.14
    <<: *networks
    volumes:
      - db-vol:/var/lib/postgresql/data
    env_file:
      - ./envs/docker.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    <<: *networks
    ports:
      - "15432:80"
    depends_on:
      - db-api
    volumes:
      - pgadmin-vol:/var/lib/pgadmin
    env_file:
      - ./envs/docker.env

networks:
  api:
    name: poc-api-network
    driver: bridge

volumes:
  db-vol:
  pgadmin-vol:

