FROM node:lts-alpine3.14

WORKDIR /poc-back
COPY package*.json ./
RUN true
COPY tsconfig*.json ./
RUN true
COPY nest-cli.json ./
RUN true
RUN npm install && npm cache clean --force
RUN npm run build

EXPOSE 8000

CMD [ "npm", "run", "start:prod" ]

