FROM node:lts-alpine3.14

WORKDIR /app
COPY package*.json ./
RUN true
COPY public ./
RUN true
COPY tsconfig.json ./
RUN true
COPY tsoa.json ./
RUN true
RUN npm install

EXPOSE 4444

CMD ["npm", "run", "dev"]
