version: "3.5"

x-networks-service-template: &networks
  networks:
    - api

services:
  poc-back:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: poc-back-container
    <<: *networks
    volumes:
      - ./src:/poc-back/src
      - ./envs:/poc-back/envs
      - ./test:/poc-back/test
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - db-back

  db-back:
    container_name: db-back-container
    image: postgres:12-alpine3.14
    command: -c fsync=off --client-min-messages=warning
    <<: *networks
    volumes:
      - db-back-vol:/var/lib/postgresql/data
    env_file:
      - ./envs/docker-dev.env

  pgadmin-back:
    image: dpage/pgadmin4
    container_name: pgadmin-back-container
    <<: *networks
    ports:
      - "15432:80"
    depends_on:
      - db-back
    volumes:
      - pgadmin-back-vol:/var/lib/pgadmin
    env_file:
      - ./envs/docker-dev.env

networks:
  api:
    name: poc-back-network
    driver: bridge

volumes:
  db-back-vol:
  pgadmin-back-vol:

