version: '3.5'

x-networks-service-template: &networks
  networks:
    - api

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: poc-back
    <<: *networks
    volumes:
      - ./src:/app/src
    ports:
      - "4444:4444"
    depends_on:
      - db
    env_file:
      - ./envs/dev.env

  db:
    image: postgres:12-alpine3.14
    command: -c fsync=off --client-min-messages=warning
    <<: *networks
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./envs/dev.env

networks:
  api:
    name: poc-back
    driver: bridge

volumes:
  db:
