name: Simple script deploy in EC2 with docker

on:
  push:
    branches:
    - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.RSA_KEY }}
        script: |
          cd ~/poc-back
          echo "Stopping docker-compose"
          docker-compose -f docker-compose.prod.yml down poc-back-prod
          echo "git pulling project"
          git pull
          echo "executing docker-compose on background"
          docker-compose -f docker-compose.prod.yml up --build poc-back-prod &> ~/api.docker-compose.log &
          echo "Finished, bye bye :)"



